### ISSUE TITLE
Unexpected token Error

### ISSUE THREAD

**Issue by dickesB2018** [BletchleyTech/aws-client-s3#1]
Hey everbody

I installed the lastest aws-client-s3 in my Node.js project and my app crashed due to an unexpected token in a node_module file from the package.

![Bildschirmfoto 2023-02-17 um 08 00 56](https://user-images.githubusercontent.com/42349778/219573029-86d1d6a7-fdc9-4725-9947-4cbe416c7752.png)

Any Idea how to resolve this?

Cheers Jakob

**Comment by Jorge644240** [comment]
Hi there Jakob,

Could you please send a screenshot of the whole error? Also, it would really help to know where the error comes from in your code.
